backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "_site/img/post"
public_folder: "/img/post"
collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["posts"]}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}